### ISSUE TITLE
[Bug] オブジェクトを左に移動させる際に当たり判定が作動しない

### ISSUE THREAD

**Issue by ystt-lita** [OR-11/Whether-collide#1]
# 概要
オブジェクト`Character`の左側に当たり判定を設定したオブジェクト`Wall`があるとき、`Character`を左に移動させて`Wall`に触れた際に停止せずすり抜ける。逆方向及び上下方向に移動する際には再現しない。

# 再現手順
1. 2つのオブジェクト`Character` `Wall`を作成
2. すべてのオブジェクトに`BoxCollider2D`、`motion`をアタッチ
3. `Character`の`motion`について、`Grounds`のサイズを1に設定し、要素に`Wall`を登録
4. `Character`に`motion#change_dummy_transform_position`もしくは`motion#movement`をもちいた移動スクリプトをアタッチ
5. プレイモードで`Wall`の右側から`Character`を衝突させる

# 期待される動作
衝突した際に`Wall`の右側で`Character`が停止し、さらに左に移動させようとしても動かない。

# 実際の動作
衝突しても停止せず、さらに左に移動させようとするとオブジェクトを通り抜けて進行する。

**Comment by ystt-lita** [comment]
issue立てるだけ立てました。見れるときに見ます

**Comment by ystt-lita** [comment]
`Wall`の右端の座標と`Character`の左端の座標が同一の場合、上記のバグは起きないようです。一度衝突するようになっても、しばらく移動させていると誤差がたまるのか再びすり抜けるようになりました。

**Comment by OR-11** [comment]
多分直りました
